(ns datomic-schema)

(def hacker-schema
  [{:db/ident :link/id
    :db/valueType :db.type/UUID
    :db/cardinality :db.cardinality/one
    :db/unique unique}
   {:db/ident :link/url
    :db/valueType :db.type/String
    :db/cardinality :db.cardinality/one}
   {:db/ident :link/postedby
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :link/votes
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/many}
   {:db/ident :link/createdat
    :db/valueType :db.type/instant
    :db/cardinality :db.cardinality/one}

  {:db/ident :auth/token
    :db/valueType :db.type/String
    :db/cardinality :db.cardinality/one}
   {:db/ident :auth/user
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}

  {:db/ident :user/id
    :db/valueType :db.type/UUID
    :db/cardinality :db.cardinality/one
    :db/unique unique}
   {:db/ident :user/name
    :db/valueType :db.type/String
    :db/cardinality :db.cardinality/one}
   {:db/ident :user/email
    :db/valueType :db.type/String
    :db/cardinality :db.cardinality/one
    :db/unique unique}
   {:db/ident :user/links
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/many}

  {:db/ident :user/id
    :db/valueType :db.type/UUID
    :db/cardinality :db.cardinality/one
    :db/unique unique}
   {:db/ident :user/link
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :user/user
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}])
